# according to https://github.com/istanbuljs/istanbuljs/tree/master/packages/nyc-config-typescript
extends: "@istanbuljs/nyc-config-typescript"

reporter:
  - html
  - lcovonly
  - clover
  # those 2 are for commandline outputs
  - text
  - text-summary
report-dir: coverage
include: 
  - "src/controllers"
  - "src/services"
  - "src/utils"
  - "src/middlewares"
  - "src/datasource"
  - "src/repository"
  - "src/config.ts"
exclude: 
  - "src/__tests__/**/*.spec.ts"
  - "src/**/*.d.ts"
exclude-after-remap: false

# Coverage gates
check-coverage: true
functions: 80
lines: 80
statements: 80
branches: 70